### ISSUE TITLE
support Pivotal Tracker

### ISSUE THREAD

**Issue by hidden-dimensions** [oursky/devops-git-label#5]
- [ ] sub-command git create git label, e.g. `docker run --rm -it devops-project-label git --github-token=XXXX --slug owner/repo`
- [ ] sub-command pivotal-tracker create pivotal tracker label, e.g. `docker run --rm -it devops-project-label pivotal-tracker --pivotal-token=XXXX --slug owner/repo`
- [ ] print help if no command provided
- [ ] adjust README

https://www.pivotaltracker.com/help/api/rest/v5#Labels

**Comment by joyzoursky** [comment]
I've written this dirty python script for my own use...
If anyone is helping on this issue can take reference from this...

**create_tracker_labels.py**
```
import requests
import sys
import json

# Check repository name
if len(sys.argv) <= 1:
    print('Please provide a PivotalTracker project id.')
    print('e.g. python create_labels.py 2400370')
    exit()
else:
    tracker_pid = sys.argv[1]

# params
tracker_token = 'mytoken'
tracker_endpoint = 'https://www.pivotaltracker.com/services/v5/projects/' + tracker_pid + '/labels'
tracker_headers = {
    'Content-Type': "application/json",
    'X-TrackerToken': tracker_token
}

def tracker_fetch_labels():
    tracker_labels = []
    res = requests.get(tracker_endpoint, headers=tracker_headers)
    res_labels = res.json()
    for res_label in res_labels:
        tracker_labels.append(res_label['name'])
    return tracker_labels

def fetch_local_labels():
    json_file = open('labels.json')
    json_str = json_file.read()
    local_labels = json.loads(json_str)
    return local_labels

def check_and_create_labels(tracker_labels, local_labels):
    for local_label in local_labels:
        if (local_label['name'] not in tracker_labels and
            local_label['name'] != 'back from acceptance'): # no need this label for pivotaltracker
            print('Creating label "%s"...' % local_label['name'])
            label = {
                "name": local_label['name']
            }
            requests.post(tracker_endpoint, headers=tracker_headers, data=json.dumps(label))

print('Fetching PivotalTracker project labels...')
tracker_labels = tracker_fetch_labels()
local_labels = fetch_local_labels()
check_and_create_labels(tracker_labels, local_labels)

```

**create_github_labels.py**

```
import requests
import sys
import json

# Check repository name
if len(sys.argv) <= 1:
    print('Please provide a GitHub repository name.')
    print('e.g. python create_labels.py sparklehealth')
    exit()
else:
    hub_repo = sys.argv[1]

# params
hub_user = 'myusername'
hub_token = 'mytoken'
hub_endpoint = 'https://api.github.com'
hub_url = hub_endpoint + '/repos/oursky/%s/labels' % hub_repo

def hub_fetch_labels():
    hub_labels = []
    res = requests.get(hub_url, auth=(hub_user, hub_token))
    res_labels = res.json()
    for res_label in res_labels:
        hub_labels.append(res_label['name'])
    return hub_labels

def fetch_local_labels():
    json_file = open('labels.json')
    json_str = json_file.read()
    local_labels = json.loads(json_str)
    return local_labels

def check_and_create_labels(hub_labels, local_labels):
    for local_label in local_labels:
        if local_label['name'] not in hub_labels:
            hub_payload = local_label
            print('Creating label "%s"...' % local_label['name'])
            res = requests.post(hub_url, auth=(hub_user, hub_token), data=json.dumps(hub_payload))

print('Fetching GitHub labels...')
hub_labels = hub_fetch_labels()
local_labels = fetch_local_labels()
check_and_create_labels(hub_labels, local_labels)

```

labels.json

```
[
  {
    "name": "back from acceptance",
    "description": "",
    "color": "fbca04"
  },
  {
    "name": "UI",
    "description": "",
    "color": "0e8a16"
  },
  {
    "name": "code quality",
    "description": "",
    "color": "ea2ee4"
  },
  {
    "name": "reported by client",
    "description": "",
    "color": "c2e0c6"
  },
  {
    "name": "reported by qa",
    "description": "",
    "color": "fef2c0"
  },
  {
    "name": "reported by team",
    "description": "",
    "color": "c5def5"
  },
  {
    "name": "bug/critical",
    "description": "> 70% users will notice a feature broken, fix immediately",
    "color": "b60205"
  },
  {
    "name": "bug/major",
    "description": "> 70% users will be affected by the issue, or any feature broken, fix asap",
    "color": "d93f0b"
  },
  {
    "name": "bug/minor",
    "description": "> 20% users will be affected by the issue, fix optionally",
    "color": "e99695"
  },
  {
    "name": "bug/trivial",
    "description": "< 20% users will be affected by the issue, fix optionally",
    "color": "f9d0c4"
  },
  {
    "name": "ux/critical",
    "description": "Almost all users will notice the issue as a problem",
    "color": "5319e7"
  },
  {
    "name": "ux/major",
    "description": "> 70% users will notice the issue as a problem",
    "color": "0052cc"
  },
  {
    "name": "ux/minor",
    "description": "> 20% users will notice the issue as a problem",
    "color": "d4c5f9"
  },
  {
    "name": "ux/trivial",
    "description": "< 20% users will notice the issue as a problem",
    "color": "bfd4f2"
  },
  {
    "name": "ui/critical",
    "description": "will affect the look and feel impression of almost all users",
    "color": "139328"
  },
  {
    "name": "ui/major",
    "description": "will affect the look and feel impression of > 70% users",
    "color": "63c11b"
  },
  {
    "name": "ui/minor",
    "description": "will affect the look and feel impression of > 20% users",
    "color": "aee246"
  },
  {
    "name": "ui/trivial",
    "description": "will affect the look and feel impression of < 20% users",
    "color": "d1ef09"
  }
]

```

**Comment by hidden-dimensions** [comment]
we not using pivotal tracker anymore, so closing this.
